/**
 * Central SEO / site configuration.
 *
 * Single source of truth for the production URL, business NAP (name, address,
 * phone), hours, and social profiles. Used by root metadata, the sitemap,
 * robots, and the structured-data (JSON-LD) helpers so everything stays in sync.
 */

export const SITE_URL = "https://www.stubborngoatbrewing.com"

export const SITE_NAME = "Stubborn Goat Brewing"

export const SITE_DESCRIPTION =
  "Stubborn Goat Brewing is a family-friendly craft brewery and taproom in West Grove, PA, pouring house-brewed beer, PA-made wine and spirits, food, and an always-fresh lineup of live music and events."

/** Short tagline used for the homepage H1 and social titles. */
export const SITE_TAGLINE = "Craft Beer, Food & Live Music in West Grove, PA"

export const BUSINESS = {
  phone: "+1-610-679-9017",
  email: "tribe@stubborngoatbrewing.com",
  streetAddress: "122 Rosehill Ave",
  addressLocality: "West Grove",
  addressRegion: "PA",
  postalCode: "19390",
  addressCountry: "US",
  latitude: 39.8224868,
  longitude: -75.8293238,
} as const

export const SOCIAL_LINKS = [
  "https://instagram.com/stubborngoatbrewing",
  "https://www.facebook.com/profile.php?id=61575081059536",
  "https://untappd.com/StubbornGoatBrewing",
  "https://share.google/fORJRGzfKSfRnhGKs",
]

/** Logo used in structured data (must be a crawlable absolute URL). */
export const LOGO_PATH = "/images/full-logo.png"

/** Representative photo of the venue, used for LocalBusiness structured data. */
export const BUSINESS_IMAGE_PATH = "/images/brewery-exterior-sunset.jpg"

/**
 * The 1200x630 social share image is generated by the file-convention route at
 * app/opengraph-image.tsx and applied site-wide, so it does not need to be
 * referenced manually in per-page metadata.
 */

/** Absolute URL helper for canonicals and structured data. */
export function absoluteUrl(path = ""): string {
  return new URL(path, SITE_URL).toString()
}

/**
 * Builds a complete Metadata object for a page.
 *
 * Next merges nested metadata objects shallowly, so a page that sets its own
 * `openGraph`/`twitter` replaces the layout's entirely. This helper restates
 * those fields so every page keeps consistent social tags and a correct
 * canonical URL. The 1200x630 share image is supplied site-wide by the
 * opengraph-image route, so it is intentionally not set here.
 */
export function pageMetadata({
  title,
  description = SITE_DESCRIPTION,
  path,
}: {
  title?: string
  description?: string
  path: string
}): import("next").Metadata {
  const socialTitle = title ? `${title} | ${SITE_NAME}` : `${SITE_NAME} | ${SITE_TAGLINE}`

  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: SITE_NAME,
      url: path,
      title: socialTitle,
      description,
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
    },
  }
}
